apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi  # In Terraform we defined EBS volume size also 20 Gi (mysql_volume_size)
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: {{ .Values.ebs.volumeId }}  # This will come from your Terraform output
    fsType: ext4
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""  # Add this line
#   hostPath:  # Remove awsElasticBlockStore and use hostPath
#     path: /var/lib/mysql-data