name: Application_CI

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["K8S_Deployment"]
    types:
      - completed 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Python
      run: |
        sudo yum update -y
        sudo yum install python3 -y
        sudo yum install -y python3-pip
        python3 -m pip install --upgrade pip

    - name: Install Docker
      run: |
        sudo yum install -y docker
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER
        newgrp docker
        sudo chmod 666 /var/run/docker.sock

    - name: Install Dependencies
      run: |
        pip install -r App/requirements.txt
        pip install pytest
        sudo yum install -y git

    - name: Run Unit Tests
      run: |
        cd App
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/test_app.py

    # - name: Run Integration Tests
    #   run: |
    #     cd App
    #     PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/test_integration.py

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest App

    - name: Trivy Security Scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

    - name: Bump Version
      id: version
      run: |
        VERSION=$(cat App/VERSION)
        NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
        echo $NEW_VERSION > App/VERSION
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit Version Bump
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add App/VERSION
        git commit -m "Bump version to ${{ env.new_version }}"
        git push