name: Application CD

on:
  push:
    branches:
      - main
    paths:
      - 'helm'
  workflow_run:
    workflows: ["Application_CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Download parameter artifact from first workflow
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GIT_PAT }}
        run-id: "12332076920"
        name: ec2-ip

    - name: Read parameters from the file and Get EC2 IP
      run: |
        EC2_IP=$(cat ec2_ip.txt | tr -d '\n\r')
        echo "EC2_IP=${EC2_IP}" >> $GITHUB_ENV
        echo "Found EC2 IP: ${EC2_IP}"


    - name: SSH and install Helm
      uses: appleboy/ssh-action@v1.2.0
      env:
          EC2_IP: ${{ env.EC2_IP }}
      with:
          host: ${{ env.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Install Helm
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod +x get_helm.sh
            ./get_helm.sh
            helm version

            # Create directory for charts
            rm -rf ~/helm-charts
            mkdir -p ~/helm-charts

    - name: Copy Helm Charts to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "helm/*"
        target: "~/helm-charts"

    - name: Helm install Applications
      uses: appleboy/ssh-action@v1.2.0
      env:
          EC2_IP: ${{ env.EC2_IP }}
      with:
          host: ${{ env.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Deploy MySQL
            pwd
            cd ~/helm-charts/helm
            pwd;ls -la
            echo "before installation"
            ls -la mysql
            helm install mysql mysql --set mysql.rootPassword=mysecurepassword

            # Deploy Python App 
            helm install python-app python-app \
              --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/flask-app \
              --set image.tag=latest
